export const de = {
  title: "Olympia — Heiligtum des Zeus und Geburtsstätte der Olympischen Spiele",
  nameLocal: "Ολυμπία - Ιερό του Δία",
  shortDescription:
    "Geburtsstätte der Olympischen Spiele, wo Athleten 1.169 Jahre lang zu Ehren des Zeus wetteiferten. Heimat eines der Sieben Weltwunder: der kolossalen Gold-Elfenbein-Statue des Zeus.",
  builder: "Verschiedene griechische Stadtstaaten und Herrscher; Zeus-Tempel entworfen vom Architekten Libon von Elis",
  historicalPeriod: "Von der mykenischen bis zur römischen Epoche (2000 v. Chr. – 400 n. Chr.)",
  description:
    "Olympia, eingebettet in das fruchtbare Tal des Flusses Alpheios auf der westlichen Peloponnes, war die heiligste Kultstätte des Zeus, des Göttervaters, und die Geburtsstätte der Olympischen Spiele — des größten athletischen und religiösen Festes der antiken Welt. Über ein Jahrtausend hinweg ruhten alle vier Jahre die Waffen in ganz Griechenland, während Athleten und Pilger zusammenströmten, um Zeus durch den Wettkampf zu ehren.\n\nDie Olympischen Spiele waren kein bloßes Sportereignis — sie waren ein heiliger Akt der Gottesverehrung. Die Athleten traten nackt und mit Olivenöl gesalbt an und brachten die Vollkommenheit ihrer Körper dem obersten Gott dar. Die Sieger wurden mit Zweigen des wilden Ölbaums bekränzt, der nach der Legende von Herakles selbst hinter dem Zeus-Tempel gepflanzt worden war. In Olympia zu siegen bedeutete, unsterblichen Ruhm zu erlangen: Bronzestatuen der Sieger säumten die Heilige Straße, und ihre Namen wurden für die Ewigkeit festgehalten.\n\nDas Heiligtum beherbergte einige der großartigsten Bauwerke der Antike. Der 457 v. Chr. vollendete Zeus-Tempel enthielt eines der Sieben Weltwunder: die kolossale chryselephantine Sitzstatue des Zeus, ein Werk des Phidias. Die etwa zwölf Meter hohe Figur zeigte Zeus mit einer Nike (der Siegesgöttin) in der Rechten und einem von einem Adler gekrönten Zepter in der Linken. Antike Besucher berichteten, dass die Statue den Eindruck erweckte, der Gott selbst sei im Tempel zugegen.\n\nDer Hera-Tempel — älter als der des Zeus — hütete die ewige Flamme, die niemals erlöschen durfte. Alle vier Jahre wurde sie mit einem Parabolspiegel, der die Sonnenstrahlen bündelte, neu entfacht — ein Ritual, das bis heute fortlebt: Das Olympische Feuer wird vor jeder Austragung der modernen Spiele nach antiker Methode in Olympia entzündet.\n\nDas Gelände umfasste ferner das Stadion (wo 45.000 Zuschauer die Wettläufe verfolgten), das Hippodrom (für Wagenrennen), das Gymnasion und die Palästra (für das Training) sowie das Philippeion — ein Rundmonument zu Ehren Philipps II. von Makedonien, des Vaters Alexanders des Großen. Von den griechischen Stadtstaaten errichtete Schatzhäuser reihten sich auf der Terrasse aneinander, jedes mit den kostbarsten Weihgaben an Zeus.\n\nDie Spiele dauerten 1.169 Jahre — von 776 v. Chr. bis zum Verbot durch Kaiser Theodosius I. im Jahr 393 n. Chr. als heidnisches Fest. Kurz darauf begruben Erdbeben und Überschwemmungen des Alpheios das Heiligtum unter meterdicken Sedimentschichten und bewahrten es, bis 1875 deutsche Archäologen die Ausgrabungen aufnahmen.",
  historicalSignificance:
    "Olympia verkörperte den Gedanken der panhellenischen Einheit — die Überzeugung, dass trotz endloser Kriege alle Griechen eine gemeinsame Kultur, gemeinsame Götter und eine gemeinsame Identität teilten. Die Olympischen Spiele waren der höchste Ausdruck dieser Einheit. Während des vor jeder Olympiade ausgerufenen «Heiligen Waffenstillstands» (Ekecheiria) verpflichteten sich alle griechischen Staaten, die Feindseligkeiten einzustellen, damit Athleten und Zuschauer sicher reisen konnten.\n\nDer Überlieferung nach begannen die Spiele 776 v. Chr., als Koroibos von Elis den Stadionlauf gewann. Dieses Datum wurde zum Ausgangspunkt der griechischen Zeitrechnung — Ereignisse wurden nach Olympiaden (Vierjahreszyklen) datiert. Im Laufe der Jahrhunderte erweiterte sich das Programm um Ringen, Faustkampf, Pankration, Wagenrennen, Fünfkampf sowie Wettbewerbe für Herolde und Trompeter.\n\nTeilnehmen durften nur freie griechische Männer (verheirateten Frauen war selbst das Zuschauen bei Todesstrafe verboten). Die Sieger stammten jedoch aus der gesamten griechischen Welt — von Sizilien bis zum Schwarzen Meer, von Nordafrika bis zur Ägäis. Ein Sieg in Olympia machte einen Mann zum Helden; seine Heimatstadt riss ein Stück ihrer Mauer nieder, um ihn willkommen zu heißen (eine Stadt mit einem solchen Champion brauchte keine Verteidigungsmauern).\n\nDie um 435 v. Chr. von Phidias geschaffene Zeus-Statue wurde zu einem der Sieben Weltwunder. Antike Quellen berichten, dass Besucher vor ihr in Tränen ausbrachen — so überwältigend war die Gegenwart des Gottes, verkörpert in Gold und Elfenbein. Die Statue wurde schließlich nach Konstantinopel überführt, wo sie 475 n. Chr. einem Brand zum Opfer fiel.\n\nDie modernen Olympischen Spiele, die Pierre de Coubertin 1896 ins Leben rief, nahmen sich bewusst das antike Vorbild zum Maßstab. Das Olympische Feuer wird noch immer nach althergebrachtem Verfahren in Olympia entzündet und von Läufern zum Austragungsort getragen. Die fünf olympischen Ringe stehen für die Kontinente, doch der Geist bleibt derselbe: ein Waffenstillstand inmitten des Konflikts, eine Feier menschlicher Höchstleistung, eine Huldigung an Ideale, die größer sind als wir selbst.",
  funFacts: [
    "Das Wort «Gymnasium» leitet sich vom griechischen gymnos (nackt) ab — die Athleten trainierten und wetteiferten unbekleidet",
    "Verheiratete Frauen, die sich heimlich zu den Spielen schlichen, sollten von einer Klippe gestürzt werden — doch es gibt keinen Beleg, dass diese Strafe je vollstreckt wurde",
    "Die Zeus-Statue war so gewaltig, dass der Gott, hätte er sich erhoben, mit dem Kopf durch das Tempeldach gestoßen wäre",
    "Milon von Kroton gewann das Ringen sechsmal in 24 Jahren — der erfolgreichste Athlet der antiken Olympia-Geschichte",
    "Die Stadionlaufstrecke maß genau 192,27 Meter — die Strecke, die Herakles in einem einzigen Atemzug zurücklegen konnte",
    "Kaiser Nero nahm am Wagenrennen teil, fiel vom Wagen, beendete das Rennen nicht, wurde aber trotzdem zum Sieger erklärt",
    "Die Sieger erhielten in Olympia nur einen Olivenkranz, doch ihre Heimatstädte belohnten sie oft mit Geld, lebenslanger Speisung und anderen Ehren",
    "Der Heilige Waffenstillstand wurde 1.169 Jahre lang eingehalten — länger, als das moderne Nationalstaatensystem existiert",
    "Die Werkstatt des Phidias in Olympia wurde später in eine christliche Kirche umgewandelt; Ausgrabungen förderten seine Werkzeuge und Gussformen zutage",
    "Der Fackellauf wurde tatsächlich von den Nationalsozialisten für die Olympischen Spiele 1936 in Berlin erfunden, nimmt aber Bezug auf die antike Flamme von Olympia",
  ],
  timeline: [
    "~2000 v. Chr. - Früheste kultische Aktivitäten im Alpheios-Tal",
    "~1200 v. Chr. - Etablierung des Zeus-Kults an der Stätte",
    "776 v. Chr. - Erste belegte Olympische Spiele; Koroibos von Elis gewinnt den Stadionlauf",
    "724 v. Chr. - Der Diaulos (Doppel-Stadionlauf) wird eingeführt",
    "708 v. Chr. - Fünfkampf und Ringen werden eingeführt",
    "688 v. Chr. - Faustkampf wird eingeführt",
    "680 v. Chr. - Wagenrennen werden eingeführt",
    "648 v. Chr. - Pankration wird eingeführt",
    "600 v. Chr. - Hera-Tempel fertiggestellt",
    "457 v. Chr. - Zeus-Tempel fertiggestellt",
    "435 v. Chr. - Zeus-Statue des Phidias aufgestellt",
    "420 v. Chr. - Sparta wegen Bruchs des Waffenstillstands von den Spielen ausgeschlossen",
    "388 v. Chr. - Philipp II. von Makedonien gewinnt das Wagenrennen",
    "356 v. Chr. - Philipp II. gewinnt das Pferderennen am selben Tag, an dem Alexander der Große geboren wird",
    "146 v. Chr. - Rom erobert Griechenland; die Spiele gehen unter römischer Aufsicht weiter",
    "67 n. Chr. - Kaiser Nero nimmt an den Spielen teil (und «gewinnt» jeden Wettbewerb)",
    "393 n. Chr. - Kaiser Theodosius I. verbietet die Olympischen Spiele",
    "426 n. Chr. - Theodosius II. ordnet die Zerstörung der Tempel an",
    "522 und 551 n. Chr. - Erdbeben verschütten die Stätte",
    "1875 - Beginn der deutschen archäologischen Ausgrabungen",
    "1936 - Erstmalige Entzündung des modernen Olympischen Feuers in Olympia",
    "1989 - Aufnahme in die UNESCO-Welterbeliste",
  ],
  tags: [
    "olympia",
    "olympische spiele",
    "zeus",
    "griechenland",
    "antike",
    "heiligtum",
    "unesco",
    "sieben weltwunder",
    "phidias",
    "stadion",
    "leichtathletik",
    "pelops",
    "herakles",
    "peloponnes",
  ],
};
