export const es = {
  title: "Olimpia — Santuario de Zeus y Cuna de los Juegos Olímpicos",
  nameLocal: "Ολυμπία - Ιερό του Δία",
  shortDescription:
    "Cuna de los Juegos Olímpicos, donde los atletas compitieron durante 1.169 años en honor a Zeus. Hogar de una de las Siete Maravillas: la colosal estatua crisoelefantina de Zeus.",
  builder: "Diversas ciudades-estado y gobernantes griegos; Templo de Zeus por el arquitecto Libón de Élide",
  historicalPeriod: "Desde el período micénico hasta la era romana (2000 a.C. – 400 d.C.)",
  description:
    "Olimpia, enclavada en el fértil valle del río Alfeo en el Peloponeso occidental, fue el recinto más sagrado consagrado a Zeus, Rey de los Dioses, y la cuna de los Juegos Olímpicos — el mayor festival atlético y religioso del mundo antiguo. Durante más de un milenio, cada cuatro años, las guerras entre los pueblos griegos se silenciaban mientras atletas y peregrinos acudían a honrar a Zeus mediante la competición.\n\nLos Juegos Olímpicos no eran un mero espectáculo deportivo: constituían un acto sagrado de culto. Los atletas competían desnudos y ungidos con aceite de oliva, ofreciendo la perfección de sus cuerpos al dios supremo. Los vencedores eran coronados con ramas de olivo silvestre cortadas del árbol sagrado que, según la leyenda, el propio Heracles había plantado detrás del Templo de Zeus. Alcanzar la victoria en Olimpia significaba conquistar una gloria inmortal; las estatuas de los campeones se alineaban a lo largo de la Vía Sacra y sus nombres quedaban grabados para la eternidad.\n\nEl santuario albergaba algunos de los monumentos más prodigiosos de la Antigüedad. El Templo de Zeus, completado en el 457 a.C., contenía una de las Siete Maravillas del Mundo: la colosal estatua crisoelefantina de Zeus entronizado, obra de Fidias. Con una altura de unos doce metros, la estatua mostraba a Zeus sosteniendo a Niké (la Victoria) en la mano derecha y un cetro coronado por un águila en la izquierda. Los visitantes de la Antigüedad aseguraban que la estatua hacía presente al dios mismo dentro del templo.\n\nEl Templo de Hera, más antiguo que el de Zeus, custodiaba la llama sagrada que ardía sin cesar. Esta llama se reencendía cada cuatro años concentrando los rayos del sol con un espejo parabólico — un ritual que pervive hasta hoy cuando la Antorcha Olímpica se enciende en Olimpia antes de cada edición moderna de los Juegos.\n\nEl recinto comprendía además el Estadio (donde 45.000 espectadores contemplaban las carreras), el Hipódromo (para las carreras de carros), el Gimnasio y la Palestra (para el entrenamiento), y el Filipeion (un memorial circular en honor a Filipo II de Macedonia, padre de Alejandro). Las Tesorerías levantadas por las ciudades-estado griegas se alineaban en la terraza, exhibiendo las ofrendas más preciadas de cada polis a Zeus.\n\nLos Juegos se celebraron durante 1.169 años, desde el 776 a.C. hasta que el emperador Teodosio I los prohibió en el 393 d.C. como festival pagano. Poco después, terremotos y las crecidas del Alfeo sepultaron el santuario bajo metros de sedimento, preservándolo hasta que los arqueólogos alemanes iniciaron las excavaciones en 1875.",
  historicalSignificance:
    "Olimpia encarnó el ideal de la unidad panhelénica — la convicción de que, a pesar de las guerras incesantes, todos los griegos compartían una cultura, unos dioses y una identidad comunes. Los Juegos Olímpicos fueron la expresión suprema de esa unidad. Durante la Tregua Sagrada (Ekecheiria), proclamada antes de cada Olimpiada, todos los estados griegos convenían en suspender las hostilidades para que atletas y espectadores pudieran viajar sin riesgo.\n\nLos Juegos comenzaron, según la tradición, en el 776 a.C. cuando Koroibos de Élide venció en la carrera del estadio (stadion). Esa fecha se convirtió en el punto de partida de la cronología griega: los acontecimientos se fechaban por Olimpiada (ciclos de cuatro años). Con el tiempo, el programa se amplió con lucha, boxeo, pancracio, carreras de carros, pentatlón y concursos para heraldos y trompetistas.\n\nSolo los varones griegos libres podían competir (a las mujeres casadas se les prohibía incluso asistir, bajo pena de muerte). Pero los vencedores procedían de todo el mundo griego — desde Sicilia hasta el Mar Negro, desde el norte de África hasta el Egeo. Una victoria en Olimpia convertía a un hombre en héroe; su ciudad derribaba un tramo de murallas para recibirlo (una ciudad con tal campeón no necesitaba defensas).\n\nLa estatua de Zeus, creada por Fidias hacia el 435 a.C., se convirtió en una de las Siete Maravillas del Mundo. Las fuentes antiguas describen cómo los visitantes rompían a llorar al contemplarla, de tan abrumadora que resultaba la presencia del dios hecha carne en oro y marfil. La estatua fue finalmente trasladada a Constantinopla, donde pereció en un incendio en el 475 d.C.\n\nLos Juegos Olímpicos modernos, resucitados por Pierre de Coubertin en 1896, se inspiraron conscientemente en el modelo antiguo. La Antorcha Olímpica sigue encendiéndose en Olimpia con métodos ancestrales y es transportada por relevistas hasta la sede de cada edición. Los cinco anillos olímpicos representan los continentes, pero el espíritu permanece intacto: una tregua ante el conflicto, una celebración de la excelencia humana, una ofrenda a ideales más grandes que nosotros mismos.",
  funFacts: [
    "La palabra «gimnasio» proviene del griego gymnos (desnudo) — los atletas entrenaban y competían sin ropa",
    "Las mujeres casadas sorprendidas colándose en los Juegos debían ser arrojadas desde un precipicio, pero no existe constancia de que el castigo se ejecutara jamás",
    "La estatua de Zeus era tan enorme que, de haberse puesto en pie, su cabeza habría atravesado el techo del templo",
    "Milón de Crotona ganó la lucha seis veces en 24 años, convirtiéndose en el atleta más laureado de la historia olímpica antigua",
    "La carrera del estadio (stadion) medía exactamente 192,27 metros — la distancia que Heracles podía recorrer sin tomar aliento",
    "El emperador Nerón compitió en la carrera de carros, se cayó de su cuadriga, no terminó la prueba, pero fue declarado vencedor",
    "Los campeones solo recibían una corona de olivo en Olimpia, pero sus ciudades solían recompensarlos con dinero, comidas gratuitas de por vida y otros honores",
    "La Tregua Sagrada fue respetada durante 1.169 años — más tiempo del que lleva existiendo el sistema moderno de Estados-nación",
    "El taller de Fidias en Olimpia fue convertido posteriormente en iglesia cristiana; las excavaciones hallaron sus herramientas y moldes",
    "El relevo de la Antorcha Olímpica fue en realidad una invención nazi para los Juegos de Berlín de 1936, aunque se inspira en la llama sagrada de Olimpia",
  ],
  timeline: [
    "~2000 a.C. - Primeras actividades de culto en el valle del Alfeo",
    "~1200 a.C. - Se establece el culto a Zeus en el lugar",
    "776 a.C. - Primeros Juegos Olímpicos documentados; Koroibos de Élide vence en el estadio",
    "724 a.C. - Se añade el díaulo (doble estadio)",
    "708 a.C. - Se incorporan el pentatlón y la lucha",
    "688 a.C. - Se incorpora el boxeo",
    "680 a.C. - Se incorporan las carreras de carros",
    "648 a.C. - Se incorpora el pancracio",
    "600 a.C. - Terminado el Templo de Hera",
    "457 a.C. - Terminado el Templo de Zeus",
    "435 a.C. - Instalada la estatua de Zeus obra de Fidias",
    "420 a.C. - Esparta es excluida de los Juegos por violar la tregua",
    "388 a.C. - Filipo II de Macedonia vence en la carrera de carros",
    "356 a.C. - Filipo II gana la carrera ecuestre el mismo día en que nace Alejandro Magno",
    "146 a.C. - Roma conquista Grecia; los Juegos prosiguen bajo supervisión romana",
    "67 d.C. - El emperador Nerón compite (y «gana» todas las pruebas)",
    "393 d.C. - El emperador Teodosio I prohíbe los Juegos Olímpicos",
    "426 d.C. - Teodosio II ordena la destrucción de los templos",
    "522 y 551 d.C. - Terremotos sepultan el yacimiento",
    "1875 - Comienzan las excavaciones arqueológicas alemanas",
    "1936 - Primera Antorcha Olímpica moderna encendida en Olimpia",
    "1989 - Declarado Patrimonio de la Humanidad por la UNESCO",
  ],
  tags: [
    "olimpia",
    "juegos olímpicos",
    "zeus",
    "grecia",
    "antigüedad",
    "santuario",
    "unesco",
    "siete maravillas",
    "fidias",
    "estadio",
    "atletismo",
    "pélope",
    "heracles",
    "peloponeso",
  ],
};
