export const fr = {
  title: "Olympie — Sanctuaire de Zeus et Berceau des Jeux olympiques",
  nameLocal: "Ολυμπία - Ιερό του Δία",
  shortDescription:
    "Berceau des Jeux olympiques, où les athlètes rivalisèrent pendant 1 169 ans en l'honneur de Zeus. Abritait l'une des Sept Merveilles du monde : la statue chryséléphantine colossale de Zeus.",
  builder: "Diverses cités-États et souverains grecs ; temple de Zeus conçu par l'architecte Libon d'Élis",
  historicalPeriod: "De l'époque mycénienne à l'ère romaine (2000 av. J.-C. – 400 apr. J.-C.)",
  description:
    "Olympie, nichée dans la vallée verdoyante de l'Alphée, dans le Péloponnèse occidental, fut le sanctuaire le plus sacré dédié à Zeus, roi des dieux, et le berceau des Jeux olympiques — la plus grande fête athlétique et religieuse du monde antique. Pendant plus d'un millénaire, tous les quatre ans, les guerres à travers la Grèce se taisaient tandis que les athlètes et les pèlerins convergeaient pour honorer Zeus par la compétition.\n\nLes Jeux olympiques n'étaient pas un simple événement sportif : ils constituaient un acte sacré de dévotion. Les athlètes concouraient nus, le corps oint d'huile d'olive, offrant la perfection de leur chair au dieu suprême. Les vainqueurs étaient couronnés de branches d'olivier sauvage coupées de l'arbre sacré qu'Héraclès lui-même, selon la légende, avait planté derrière le temple de Zeus. Vaincre à Olympie, c'était conquérir la gloire immortelle ; les statues des champions bordaient la Voie Sacrée et leurs noms étaient gravés pour l'éternité.\n\nLe sanctuaire abritait quelques-uns des monuments les plus prodigieux de l'Antiquité. Le temple de Zeus, achevé en 457 av. J.-C., renfermait l'une des Sept Merveilles du monde : la statue chryséléphantine colossale de Zeus trônant, œuvre de Phidias. Haute d'une douzaine de mètres, elle figurait Zeus tenant Nikè (la Victoire) dans la main droite et un sceptre surmonté d'un aigle dans la gauche. Les visiteurs de l'Antiquité rapportaient que la statue semblait rendre le dieu lui-même présent dans le sanctuaire.\n\nLe temple d'Héra, antérieur à celui de Zeus, abritait la flamme sacrée qui brûlait perpétuellement. Cette flamme était ravivée tous les quatre ans au moyen d'un miroir parabolique concentrant les rayons du soleil — un rituel qui perdure aujourd'hui : la flamme olympique est toujours allumée à Olympie avant chaque édition des Jeux modernes.\n\nLe site comprenait également le stade (où 45 000 spectateurs assistaient aux courses), l'hippodrome (pour les courses de chars), le gymnase et la palestre (pour l'entraînement), ainsi que le Philippéion (un mémorial circulaire en l'honneur de Philippe II de Macédoine, père d'Alexandre). Les trésors bâtis par les cités-États grecques s'alignaient sur la terrasse, exposant leurs plus belles offrandes à Zeus.\n\nLes Jeux se déroulèrent pendant 1 169 ans, de 776 av. J.-C. jusqu'à leur interdiction par l'empereur Théodose Iᵉʳ en 393 apr. J.-C., qui les considérait comme un festival païen. Peu après, des séismes et les crues de l'Alphée ensevelirent le sanctuaire sous plusieurs mètres d'alluvions, le préservant jusqu'à ce que les archéologues allemands entament les fouilles en 1875.",
  historicalSignificance:
    "Olympie incarnait l'idéal d'unité panhellénique — la conviction que, malgré des guerres incessantes, tous les Grecs partageaient une culture, des dieux et une identité communs. Les Jeux olympiques en étaient l'expression suprême. Lors de la Trêve sacrée (Ekecheiria), proclamée avant chaque olympiade, tous les États grecs convenaient de suspendre les hostilités afin que les athlètes et les spectateurs puissent voyager en sécurité.\n\nSelon la tradition, les Jeux débutèrent en 776 av. J.-C. lorsque Koroïbos d'Élis remporta le stadion (course à pied). Cette date devint le point de départ de la chronologie grecque — les événements étaient datés par olympiade (cycle de quatre ans). Le programme s'enrichit au fil des siècles : lutte, boxe, pancrace, courses de chars, pentathlon, concours de hérauts et de trompettistes.\n\nSeuls les hommes grecs libres pouvaient concourir (les femmes mariées n'avaient pas même le droit d'assister aux épreuves, sous peine de mort). Mais les vainqueurs venaient de tout le monde grec — de la Sicile à la mer Noire, de l'Afrique du Nord à l'Égée. Une victoire à Olympie faisait d'un homme un héros ; sa cité abattait un pan de muraille pour l'accueillir (une cité pourvue d'un tel champion n'avait nul besoin de remparts).\n\nLa statue de Zeus, réalisée par Phidias vers 435 av. J.-C., devint l'une des Sept Merveilles du monde. Les sources antiques racontent que les visiteurs éclataient en sanglots en la contemplant, tant la présence du dieu, rendue manifeste dans l'or et l'ivoire, les submergeait. La statue fut finalement transférée à Constantinople, où elle périt dans un incendie en 475 apr. J.-C.\n\nLes Jeux olympiques modernes, ressuscités par Pierre de Coubertin en 1896, s'inspirèrent délibérément du modèle antique. La flamme olympique est toujours allumée à Olympie selon les méthodes ancestrales, puis portée par des relayeurs jusqu'au lieu de la compétition. Les cinq anneaux olympiques représentent les continents, mais l'esprit demeure le même : une trêve au cœur du conflit, une célébration de l'excellence humaine, une offrande à des idéaux qui nous dépassent.",
  funFacts: [
    "Le mot « gymnase » vient du grec gymnos (nu) — les athlètes s'entraînaient et concouraient entièrement nus",
    "Les femmes mariées surprises à se faufiler dans le stade devaient être précipitées du haut d'une falaise, mais aucun cas d'exécution n'est attesté",
    "La statue de Zeus était si imposante que, s'il s'était levé de son trône, sa tête aurait percé le toit du temple",
    "Milon de Crotone remporta la lutte six fois en vingt-quatre ans — l'athlète le plus titré de l'histoire olympique antique",
    "La course du stade (stadion) mesurait exactement 192,27 mètres — la distance qu'Héraclès pouvait parcourir en une seule expiration",
    "L'empereur Néron participa à la course de chars, chuta de son attelage, n'acheva jamais la course, mais fut tout de même déclaré vainqueur",
    "Les vainqueurs ne recevaient qu'une couronne d'olivier sauvage à Olympie, mais leur cité natale les récompensait souvent par de l'argent, des repas gratuits à vie et d'autres honneurs",
    "La Trêve sacrée fut respectée pendant 1 169 ans — plus longtemps que le système moderne des États-nations n'existe",
    "L'atelier de Phidias à Olympie fut ultérieurement converti en église chrétienne ; les fouilles y ont mis au jour ses outils et ses moules",
    "Le relais de la flamme olympique fut en réalité inventé par les nazis pour les Jeux de Berlin de 1936, bien qu'il fasse référence à la flamme antique d'Olympie",
  ],
  timeline: [
    "~2000 av. J.-C. - Premières activités cultuelles dans la vallée de l'Alphée",
    "~1200 av. J.-C. - Le culte de Zeus s'établit sur le site",
    "776 av. J.-C. - Premiers Jeux olympiques attestés ; Koroïbos d'Élis remporte le stadion",
    "724 av. J.-C. - Ajout du diaule (double stadion)",
    "708 av. J.-C. - Ajout du pentathlon et de la lutte",
    "688 av. J.-C. - Ajout de la boxe",
    "680 av. J.-C. - Ajout des courses de chars",
    "648 av. J.-C. - Ajout du pancrace",
    "600 av. J.-C. - Achèvement du temple d'Héra",
    "457 av. J.-C. - Achèvement du temple de Zeus",
    "435 av. J.-C. - Installation de la statue de Zeus par Phidias",
    "420 av. J.-C. - Sparte exclue des Jeux pour violation de la trêve",
    "388 av. J.-C. - Philippe II de Macédoine remporte la course de chars",
    "356 av. J.-C. - Philippe II gagne la course équestre le jour même de la naissance d'Alexandre le Grand",
    "146 av. J.-C. - Rome conquiert la Grèce ; les Jeux se poursuivent sous contrôle romain",
    "67 apr. J.-C. - L'empereur Néron concourt (et « remporte » toutes les épreuves)",
    "393 apr. J.-C. - L'empereur Théodose Iᵉʳ interdit les Jeux olympiques",
    "426 apr. J.-C. - Théodose II ordonne la destruction des temples",
    "522 et 551 apr. J.-C. - Des séismes ensevelissent le site",
    "1875 - Début des fouilles archéologiques allemandes",
    "1936 - Première flamme olympique moderne allumée à Olympie",
    "1989 - Inscription au patrimoine mondial de l'UNESCO",
  ],
  tags: [
    "olympie",
    "jeux olympiques",
    "zeus",
    "grèce",
    "antiquité",
    "sanctuaire",
    "unesco",
    "sept merveilles",
    "phidias",
    "stade",
    "athlétisme",
    "pélops",
    "héraclès",
    "péloponnèse",
  ],
};
