export const tr = {
  title: "Olimpiya — Zeus Tapınağı ve Olimpiyat Oyunlarının Doğduğu Yer",
  nameLocal: "Ολυμπία - Ιερό του Δία",
  shortDescription:
    "Olimpiyat Oyunlarının doğduğu yer; sporcular 1.169 yıl boyunca Zeus'un şerefine yarıştı. Dünyanın Yedi Harikasından birinin — devasa altın-fildişi Zeus heykelinin — yurduydu.",
  builder: "Çeşitli Yunan şehir devletleri ve hükümdarlar; Zeus Tapınağı, Elisli mimar Libon tarafından tasarlandı",
  historicalPeriod: "Miken Döneminden Roma Dönemine (MÖ 2000 – MS 400)",
  description:
    "Olimpiya, Batı Peloponnesos'ta Alfeos Nehri'nin yemyeşil vadisinde kurulmuş, tanrıların kralı Zeus'a adanmış en kutsal mabet alanı ve Olimpiyat Oyunlarının — antik dünyanın en büyük atletizm ve din şöleninin — doğum yeriydi. Bin yılı aşkın bir süre boyunca, her dört yılda bir, Yunanistan genelinde savaşlar durur, sporcular ve hacılar Zeus'u yarışmayla onurlandırmak için bir araya gelirdi.\n\nOlimpiyat Oyunları yalnızca bir spor etkinliği değil, kutsal bir ibadet eylemiydi. Sporcular çıplak ve zeytinyağıyla yağlanmış olarak yarışır, bedenlerinin mükemmelliğini baş tanrıya sunarlardı. Galiplerin başına, efsaneye göre Herakles'in bizzat Zeus Tapınağı'nın arkasına diktiği kutsal yabani zeytin ağacından kesilen dallardan örülmüş taçlar konulurdu. Olimpiya'da kazanmak ölümsüz bir şan demekti; şampiyonların heykelleri Kutsal Yol boyunca sıralanır, adları sonsuza dek kayda geçirilirdi.\n\nKutsal alan, antik dünyanın en muhteşem anıtlarından bazılarını barındırıyordu. MÖ 457'de tamamlanan Zeus Tapınağı, Dünyanın Yedi Harikasından birini saklıyordu: Phidias'ın elinden çıkma, altın ve fildişinden yapılmış devasa taht üzerindeki Zeus heykeli. Yaklaşık on iki metre yüksekliğindeki heykel, Zeus'u sağ elinde Nike'yi (Zafer Tanrıçası), sol elinde kartal figürlü bir asayı tutarken tasvir ediyordu. Antik çağ ziyaretçileri, heykelin tapınağa tanrının bizzat gelmiş olduğu hissini verdiğini anlatırlardı.\n\nZeus Tapınağı'ndan daha eski olan Hera Tapınağı, hiç sönmeyen kutsal alevi muhafaza ediyordu. Bu alev, her dört yılda bir güneş ışınlarını odaklayan parabolik bir aynayla yeniden yakılırdı — bugün de süren bir gelenek: Modern Olimpiyat Oyunlarının her birinden önce Olimpiyat Meşalesi Olimpiya'da aynı yöntemle tutuşturulur.\n\nAlan ayrıca Stadyumu (45.000 seyircinin koşu yarışlarını izlediği yer), Hipodromu (araba yarışları için), Gymnasium ve Palestra'yı (antrenman için) ve Philippeion'u (Büyük İskender'in babası II. Filip'e adanmış dairesel anıt) kapsıyordu. Yunan şehir devletlerinin inşa ettiği hazine binaları terasın üzerinde sıralanmış, her biri Zeus'a sunulan en değerli adaklarını sergiliyordu.\n\nOyunlar 1.169 yıl sürdü — MÖ 776'dan, İmparator I. Theodosius'un onları pagan festivali olarak yasakladığı MS 393'e kadar. Kısa süre sonra depremler ve Alfeos Nehri'nin taşkınları kutsal alanı metrelerce alüvyon altına gömerek korudu; ta ki 1875'te Alman arkeologlar kazılara başlayana dek.",
  historicalSignificance:
    "Olimpiya, Panhelenik birlik idealini — sürekli savaşlara rağmen tüm Yunanlıların ortak bir kültür, ortak tanrılar ve ortak bir kimlik paylaştığı inancını — somutlaştırıyordu. Olimpiyat Oyunları bu birliğin en yüce ifadesiydi. Her Olimpiyat öncesinde ilan edilen Kutsal Ateşkes (Ekecheiria) süresince tüm Yunan devletleri düşmanlıklarını askıya almayı kabul ederdi; böylece sporcular ve seyirciler güvenle yolculuk yapabilirdi.\n\nGeleneğe göre Oyunlar MÖ 776'da, Elisli Koroibos'un stadion (ayak yarışı) yarışmasını kazanmasıyla başladı. Bu tarih, Yunan kronolojisinin başlangıç noktası oldu — olaylar Olimpiyat dönemlerine (dört yıllık çevrimler) göre tarihlendirildi. Program yüzyıllar içinde güreş, boks, pankration, araba yarışı, pentatlon ve ulak ile borazancı yarışmalarıyla genişledi.\n\nYalnızca özgür Yunan erkekleri yarışabilirdi (evli kadınların seyretmesi bile ölüm cezasıyla yasaklanmıştı). Ancak galipleri tüm Yunan dünyası yetiştiriyordu — Sicilya'dan Karadeniz'e, Kuzey Afrika'dan Ege'ye. Olimpiya'da kazanmak bir adamı kahraman yapardı; şehri onu karşılamak için surlarında bir gedik açardı (böyle bir şampiyona sahip bir şehrin surlarla savunmaya ihtiyacı yoktu).\n\nPhidias'ın MÖ 435 civarında yaptığı Zeus heykeli, Dünyanın Yedi Harikasından biri oldu. Antik kaynaklar, ziyaretçilerin heykelin önünde gözyaşlarına boğulduğunu anlatır; altın ve fildişiyle cisimleşmiş tanrısal varoluş o denli güçlüydü. Heykel sonunda Konstantinopolis'e taşındı ve MS 475'te bir yangında yok oldu.\n\nPierre de Coubertin'in 1896'da canlandırdığı Modern Olimpiyat Oyunları, bilinçli olarak antik modeli örnek aldı. Olimpiyat Meşalesi bugün hâlâ kadim yöntemlerle Olimpiya'da yakılır ve koşucular tarafından yarışma şehrine taşınır. Beş halka kıtaları simgeler, ama ruh aynı kalır: çatışma ortasında bir ateşkes, insani mükemmelliğin kutlanması, kendimizden büyük ideallere sunulan bir adak.",
  funFacts: [
    "\"Gymnasium\" sözcüğü Yunanca gymnos'tan (çıplak) gelir — sporcular çıplak antrenman yapar ve yarışırdı",
    "Oyunlara gizlice giren evli kadınların uçurumdan atılması gerekiyordu; ancak bu cezanın uygulandığına dair hiçbir kayıt yoktur",
    "Zeus heykeli öylesine devasa idi ki, ayağa kalksaydı başı tapınağın çatısını delerdi",
    "Krotonlu Milon, 24 yılda altı kez güreşte şampiyon oldu — antik Olimpiyat tarihinin en başarılı sporcusu",
    "Stadion koşu mesafesi tam olarak 192,27 metreydi — Herakles'in tek nefeste koşabileceği uzaklık",
    "İmparator Nero araba yarışına katıldı, arabasından düştü, yarışı bitiremedi ama yine de şampiyon ilan edildi",
    "Galiplere Olimpiya'da yalnızca bir zeytin dalı çelengi verilirdi; ancak memleketleri genellikle para, ömür boyu ücretsiz yemek ve başka onurlarla ödüllendirirdi",
    "Kutsal Ateşkes 1.169 yıl boyunca hemen hemen kesintisiz uygulandı — modern ulus-devlet sisteminden çok daha uzun",
    "Phidias'ın Olimpiya'daki atölyesi daha sonra bir Hristiyan kilisesine dönüştürüldü; kazılarda aletleri ve kalıpları bulundu",
    "Olimpiyat Meşalesi taşıma töreni aslında 1936 Berlin Olimpiyatları için Naziler tarafından icat edildi, ancak Olimpiya'daki antik aleve atıfta bulunur",
  ],
  timeline: [
    "~MÖ 2000 - Alfeos vadisinde bilinen en eski kült faaliyetleri",
    "~MÖ 1200 - Zeus kültünün bu alanda kurulması",
    "MÖ 776 - Kayıtlara geçen ilk Olimpiyat Oyunları; Elisli Koroibos stadion yarışını kazandı",
    "MÖ 724 - Diaulos (çift stadion) yarışması eklendi",
    "MÖ 708 - Pentatlon ve güreş eklendi",
    "MÖ 688 - Boks eklendi",
    "MÖ 680 - Araba yarışı eklendi",
    "MÖ 648 - Pankration eklendi",
    "MÖ 600 - Hera Tapınağı tamamlandı",
    "MÖ 457 - Zeus Tapınağı tamamlandı",
    "MÖ 435 - Phidias'ın Zeus heykeli yerleştirildi",
    "MÖ 420 - Sparta, ateşkesi ihlal ettiği için Oyunlardan men edildi",
    "MÖ 388 - Makedon Kralı II. Filip araba yarışını kazandı",
    "MÖ 356 - II. Filip at yarışını kazandı; aynı gün İskender Büyük doğdu",
    "MÖ 146 - Roma Yunanistan'ı fethetti; Oyunlar Roma denetiminde sürdü",
    "MS 67 - İmparator Nero yarıştı (ve her dalda \"kazandı\")",
    "MS 393 - İmparator I. Theodosius Olimpiyat Oyunlarını yasakladı",
    "MS 426 - II. Theodosius tapınakların yıkılmasını emretti",
    "MS 522 ve 551 - Depremler alanı gömdü",
    "1875 - Alman arkeolojik kazılar başladı",
    "1936 - İlk modern Olimpiyat Meşalesi Olimpiya'da yakıldı",
    "1989 - UNESCO Dünya Mirası Listesi'ne alındı",
  ],
  tags: [
    "olimpiya",
    "olimpiyat oyunları",
    "zeus",
    "yunanistan",
    "antik",
    "kutsal alan",
    "unesco",
    "yedi harika",
    "phidias",
    "stadyum",
    "atletizm",
    "pelops",
    "herakles",
    "peloponnesos",
  ],
};
